### ISSUE TITLE
can I execute a sql by cursor?

### ISSUE THREAD

**Issue by yuchanns** [05bit/peewee-async#117]
when I use peewee, I can execute the sql by a `cursor()` function like this:
```python
database.cursor().execute('SELECT `uid`, `uname`, `gender` FROM `user` WHERE `uid`=10001')
```
or by a `execute_sql()` function:
```python
database.execute_sql('SELECT `uid`, `uname`, `gender` FROM `user` WHERE `uid`=10001')
```
while I found none of them with peewee_async.
do u have a plan to add some function?

**Comment by rudyryk** [comment]
@yuchanns Not sure that this is part of documented API in peewee. Why not use `RawQuery`?

**Comment by rudyryk** [comment]
Aha, I see, there's `Database` [API docs](http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.execute_sql) with many methods. Well, I was not thinking about that as a scope of this project. Because for SQL queries you can go with `aiopg` or `aiomysql` directly. The idea of ORM it abstraction on top os SQL and if I would not need such abstraction, then I'd better use database interface directly.
