### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by mrbox** [05bit/peewee-async#12]
Hi, it's a great project - finally I can use normal DB with asyncio. However it seems that transactions doesn't work:

```
    object = await peewee_async.create_object(TestModel, text="FOO")
    obj_id = object.id
    try:
        with database.atomic() as txn:
            object.text = "BAR"
            print(await peewee_async.update_object(object))
            raise AttributeError("AAAA")

    except AttributeError as e:
        object = await peewee_async.get_object(TestModel, TestModel.id==obj_id)
        print("TEXT:", object.text)
```

gives 

```
1
TEXT: BAR
```

At the moment I have no clue, how could I fix this by myself- if you could give me some hints, I'll be more than happy to contribute.

**Comment by rudyryk** [comment]
Hi @mrbox! :)

Using transactions is possible bit tricky. Here's a quick note on that:
https://aiopg.readthedocs.org/en/stable/core.html#transactions

As a workaround we could execute "BEGIN" and "COMMIT" queries directly via database. I think we may add support of raw SQL queries via `execute()`:

```python
yield from execute('BEGIN;')
await peewee_async.update_object(object)
yield from execute('COMMIT;')
```

And in order to use `with` statement we need async context managers that is only supported since Python 3.5: https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with

**Comment by rudyryk** [comment]
@mrbox Jakub, thank you for contribution! I've refactored tests to have a single entry point, renamed database methods to have `_async()` part as suffix (not prefix) and updated docs.

0.4 version in now on PyPi :)

**Comment by rudyryk** [comment]
Closing this issue. Created separate one for bug with connection pool #14

**Comment by rudyryk** [comment]
I'm reopening the issue, because I believe we need to rethink transactions implementation from bottom up.

Current implementation may **occasionally** work, but when running several transactions in parallel tasks it fails almost every time, and there's no surprise - the logic copied from multi-threaded environment is not adapted to single-threaded actually.

Here's a basic test running empty simultaneous transactions - doesn't pass:
https://github.com/05bit/peewee-async/blob/master/tests/tests_py35.py#L73

The correct implementation, I suppose, must store all transaction related data in per-task (e.g. "task locals"). I'm going to move transactions logic development to separate `transactions` branch to have hands free on publishing updates.

**Comment by rudyryk** [comment]
Also, there's a note on _autocommit mode_ in the `aiopg` docs:
https://aiopg.readthedocs.org/en/stable/core.html#aiopg-core-transactions

> While aiopg works only in autocommit mode it is still possible to use SQL transactions.

That means we don't need to switch mode at all.

**Comment by rudyryk** [comment]
Closing this issue for now, I hope won't need to reopen :)
