### ISSUE TITLE
AttributeError: 'Manager' object has no attribute 'commit_select'

### ISSUE THREAD

**Issue by sscondie** [05bit/peewee-async#37]
What I believe is simple code is returning an opaque error.  The call is

```python
async def _get_acct_by_userid(self,user_id):
    ah = await db.execute(AccountHolder.select().where(AccountHolder.userid == user_id))
    if ah.exists():
       return ah.get()
    else:
        return None
```

but the output I get is `AttributeError: 'Manager' object has no attribute 'commit_select'`

Am I doing something wrong here?

**Comment by rudyryk** [comment]
@sscondie It's unclear, what is `db`? And how the model is defined? Seems like you're using `Manager` as model's `Meta.database`, but I'm not sure.

Also, the code you've provided won't work, because the result of `await execute(...)` will return iterable object of `AccountHolder` instances, and it doesn't contain `.exist()` method.

The code should be like that:

```python
database = peewee_async.PooledPostgresqlDatabase('test')
db = peewee_async.Manager(database)

class AccountHolder(peewee.Model):
     class Meta:
          database = database

async def _get_acct_by_userid(self, user_id):
    try:
         obj = await db.get(user_id=user_id)
    except AccountHolder.DoesNotExist:
         pass
```

Or you may replace `obj = await db.get(user_id=user_id)` with the more complex select:

```python
query = await db.get(AccountHolder.select().where(AccountHolder.user_id == user_id))
```
